---
- name: backup
  hosts: routers
  gather_facts: false
  tasks:
    - name: backup-file create
      routeros_command:
        commands: "/system backup save password=_dN4eS4oit encryption=aes-sha256 name={{ file_name }}"
    - name: backup-resource create
      routeros_command:
        commands: /export file={{ file_name }}
    - name: backup-file download
      ansible.netcommon.net_get:
        src: "{{ file_name }}.backup"
        dest: /home/addansible/mikrotik_backup/backup/{{ file_name }}_{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S')>
        protocol: sftp
